// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkgdT40JO4KUusLzVnAXC3cNf9SUNRQsQ',
    appId: '1:256775926702:web:f4778cb475a42d5e67ce3f',
    messagingSenderId: '256775926702',
    projectId: 'finlog-60acc',
    authDomain: 'finlog-60acc.firebaseapp.com',
    storageBucket: 'finlog-60acc.firebasestorage.app',
    measurementId: 'G-EDY9JL62S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Q2FuBDFzGmTvMXofjF_8gEgIj7l-N4I',
    appId: '1:256775926702:android:cd0fdf524de5e7e867ce3f',
    messagingSenderId: '256775926702',
    projectId: 'finlog-60acc',
    storageBucket: 'finlog-60acc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVelfSmnxC_lW24CFyiB0iXQwhP7jDf1k',
    appId: '1:256775926702:ios:73b7c33620de62f667ce3f',
    messagingSenderId: '256775926702',
    projectId: 'finlog-60acc',
    storageBucket: 'finlog-60acc.firebasestorage.app',
    iosBundleId: 'com.example.finlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVelfSmnxC_lW24CFyiB0iXQwhP7jDf1k',
    appId: '1:256775926702:ios:73b7c33620de62f667ce3f',
    messagingSenderId: '256775926702',
    projectId: 'finlog-60acc',
    storageBucket: 'finlog-60acc.firebasestorage.app',
    iosBundleId: 'com.example.finlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkgdT40JO4KUusLzVnAXC3cNf9SUNRQsQ',
    appId: '1:256775926702:web:5e81344b20e1cc7367ce3f',
    messagingSenderId: '256775926702',
    projectId: 'finlog-60acc',
    authDomain: 'finlog-60acc.firebaseapp.com',
    storageBucket: 'finlog-60acc.firebasestorage.app',
    measurementId: 'G-ELR89DBNQM',
  );
}
